# This is a basic workflow to help you get started with Actions

name: Mobile Build

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches:
      - 'test'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  PROJECT: ChatAI.apk

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build_mobile:
    name: Android Build
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'oracle' # See 'Supported distributions' for available options
          java-version: '17'

      # Setup the flutter environment.
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      # Get flutter dependencies & Build app
      - run: flutter pub get
      - run: flutter pub run build_runner build --delete-conflicting-outputs
      - run: flutter build apk --obfuscate --split-debug-info=./
      - run: |
          APK_PATH=$(find . -name "*-release.apk" | head -1)
          if [[ -z ${APK_PATH} ]]; then 
            echo "No .apk were found"
          else  
            mv "${APK_PATH}" "./${PROJECT}"
          fi

      # Upload generated apk to the artifacts.
      - id: diawi
        uses: rnkdsh/action-upload-diawi@v1.5.5
        with:
          token: ${{ secrets.DIAWI_TOKEN }}
          file: ./ChatAI.apk
          recipients: mohamedamine.ghimeji@value.com.tn

      - uses: actions/upload-artifact@v4
        with:
          name: ChatAI
          path: ./ChatAI.apk





